name: Auto Tag on New Commit

on:
  push:
    branches:
      - main  # Change to your desired branch

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get current date and time
        id: date
        run: echo "TAG_NAME=auto-$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

      - name: Create Git tag
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git tag $TAG_NAME
          git push origin $TAG_NAME
