name: Enforce Feature Branch Merge

on:
  pull_request:
    branches:
      - main  # Only run this check when merging *into* main

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check if source branch is allowed to merge into main
        run: |
          echo "Checking branch name..."
          BRANCH_NAME="${{ github.head_ref }}"
          BASE_BRANCH="${{ github.base_ref }}"
          echo "Source Branch: $BRANCH_NAME"
          echo "Target Branch: $BASE_BRANCH"
          
          if [[ "$BASE_BRANCH" == "main" && ! "$BRANCH_NAME" =~ ^feature(/.*)?$ ]]; then
            echo "❌ ERROR: Only branches starting with 'feature/' can be merged into 'main'."
            exit 1
          else
            echo "✅ Branch name check passed."
          fi
