name: Enforce Feature Branch Merge

on:
  pull_request:
    branches:
      - main

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check if source branch starts with 'feature'
        run: |
          echo "Checking branch name..."
          BRANCH_NAME="${{ github.head_ref }}"
          BASE_BRANCH="${{ github.base_ref }}"
          echo "Source Branch: $BRANCH_NAME"
          echo "Target Branch: $BASE_BRANCH"
          
          if [[ "$BASE_BRANCH" == "main" && ! "$BRANCH_NAME" =~ ^feature(_.*)?$ ]]; then
            echo "❌ ERROR: Only branches starting with 'feature' can be merged into 'main'."
            exit 1
          else
            echo "✅ Branch name check passed."
          fi
