name: Enforce Feature Branch Merge

on:
  pull_request:

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure branch name starts with 'feature'
        run: |
          echo "Checking branch name..."
          BRANCH_NAME=${{ github.head_ref }}
          echo "Branch Name is: $BRANCH_NAME"
          if [[ ! "$BRANCH_NAME" =~ ^feature(_.*)?$ ]]; then
            echo "ERROR: Branch name '$BRANCH_NAME' does not start with 'feature'."
            exit 1
          else
            echo "Branch name is valid: '$BRANCH_NAME'."
          fi
